mod pallet_town_outside; pub fn load_pallet_town_outside() { pallet_town_outside::load(); }
mod player_house; pub fn load_player_house() { player_house::load(); }
mod player_room; pub fn load_player_room() { player_room::load(); }
// Autogenerated Code
